### ISSUE TITLE
[SPELL]Priest Shadowform

### ISSUE THREAD

**Issue by xlollomanx** [AzerothShard/AzerothShard-Ita-Wotlk#11]
La state [Shadowform](http://wotlk.openwow.com/spell=41912) del priest non funziona correttamente. Nel caso si casti in successione una cura e subito la shadowform prima della fine del gcd questa si bugga e non permette il recast della shadowform. La cosa è piuttosto fastidiosa sopratutto in pvp perchè si è costretti a tenere d'occhio la fine del gcd. L' unico modo per risolvere è riloggare.

**Comment by ShinDarth** [comment]
a

**Comment by Jagermaister95** [comment]
Testato e appurato che il bug è presente. Provvederemo il prima possibile a sistemarlo.
Grazie per la segnalazione.

**Comment by mik1893** [comment]
il fix e' stato eseguito e in attesa di essere messo sul server principale

**Comment by mik1893** [comment]
Fixato da domani 09/06/2015 su server di gioco
