### ISSUE TITLE
Bug Glyph of Arcane Blast

### ISSUE THREAD

**Issue by silfy** [AzerothShard/AzerothShard-Ita-Wotlk#13]
Il Glifo dell'Arcane Blast non funziona, dovrebbe aumentare del 3% il bonus danni dell'arcane blast a stack fino ad un totale di 4 stack ed un bonus complessivo del 12%. Una volta imparato il Glifo viene correttamente segnato sulla spell ma quando si usa l'incantesimo "Arcane Blast" il buff che appare al lato segna ancora 15% anzichè 18% non donando l'incremento. Il bug è abbastanza grave per la spec Arcane contando che è il Glifo principale della spec.

**Comment by Jagermaister95** [comment]
Testato e appurato che il bug è presente. Provvederemo il prima possibile a sistemarlo.
Grazie per la segnalazione.

**Comment by mik1893** [comment]
potrebbe essere buggo solo il tooltip della spell (ovvero applica il 3% ma non appare)
@Jagermaister95 puoi darci un occhiata e confermarmi se e' bug completo o solo tooltip?

**Comment by Jagermaister95** [comment]
appurato che è solo un problema visvo il danno è effettivamente aumentato.il glfio risulta quindi funzionante

**Comment by mik1893** [comment]
ok - lascio aperto per la parte del tooltip anche se non credo che riusciremo a fixarla (c'e una seria possibilita che fosse cosi anche su retail, non tutti I talenti vengono riflessi nei tooltp)

**Comment by mik1893** [comment]
ok il tooltip non puo essere modificato - e' cosi sul client 
chiudo
