### ISSUE TITLE
[SPELL] Focus Magic

### ISSUE THREAD

**Issue by silfy** [AzerothShard/AzerothShard-Ita-Wotlk#14]
La spell Focus Magic che si apprende con un talento in Arcane non funziona. Il Focus Magic dovrebbe donare 3% di crit su un friendly target, quando questi critta Focus magic si attiva donando di rimando un 3% di crit sul mago che ha castato l'incantesimo. Qui Focus Magic semplicemente quando l'alleato critta la spell il buff scompare non fornendo alcun bonus al mago rendendo la spell e quindi il talento inutile. Ricordo che pochi mesi fa funzionava correttamente poi si è buggato all'improvviso, visto l'importanza del talento sia in pvp che in pve ho voluto segnararlo.

**Comment by Jagermaister95** [comment]
Testato e appurato che il bug è presente. Provvederemo il prima possibile a sistemarlo.
Grazie per la segnalazione.

**Comment by mik1893** [comment]
fixato e da mettere sul server principale

**Comment by mik1893** [comment]
Fixato da domani 09/06/2015 su server di gioco
