### ISSUE TITLE
Succubus seduction bug e vari bug su pet

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Ita-Wotlk#19]
La succube non casta seduction sul target se prima non fa un meele swing su di esso, ed ogni volta si deve ripetere il gioco. Quando si casta seduction e di conseguenza non parte, consuma il dr e di conseguenza anche quello del fear. 

Non so se questo possa esservi di aiuto ... https://github.com/TrinityCore/TrinityCore/issues/16628

Continuando con i bug dei pet non vanno verso il target per fare il cc, silence o quello che sia e vanno fuori dalla mappa dove si trovano. https://github.com/TrinityCore/TrinityCore/issues/16647

Sempre per i pet c'è il bug del risummon ovvero quando un pet ha X vita, X dot, Xhot risummonando un nuovo pet riprende gli identici parametri ( buff debuff vita ) del precedente e quindi tocca prima aspettare che il pet iniziale muoia per risummonarlo ... Non sono riuscito a trovare qualcosa su trinity inerente a questo bug

**Comment by Yehonal** [comment]
Vanno creati 2 report differenti ( siccome il primo bug è stato fixato )

Se possibile continua a linkare i report da trinitycore così da velocizzare il lavoro. Se la segnalazione su TC non esiste, andrà creata...possiamo farlo noi ma devi essere il più descrittivo possibile:

1) descrizione

2) cosa dovrebbe fare

3) step per riprodurlo

In modo tale che possiamo tradurla e reportarla su TC

Chiudo questa.
Grazie
