### ISSUE TITLE
Bug resummon lock's pet

### ISSUE THREAD

**Issue by pati3nc3** [AzerothShard/AzerothShard-Ita-Wotlk#21]
Sempre per i pet c'è il bug del risummon ovvero quando un pet ha Xvita, Xdot, Xhot risummonando un nuovo pet riprende gli identici parametri ( buff debuff vita ) del precedente e quindi tocca prima aspettare che il pet iniziale muoia per risummonarlo ... Non sono riuscito a trovare qualcosa su trinity inerente a questo bug

**Comment by pati3nc3** [comment]
https://github.com/TrinityCore/TrinityCore/issues/873

Sotto nei commenti dovrebbe esserci il fix

**Comment by Yehonal** [comment]
Il fix è online
