### ISSUE TITLE
[SPELL] Arcane Missile

### ISSUE THREAD

**Issue by silfy** [AzerothShard/AzerothShard-Ita-Wotlk#23]
Dopo l'ultimo FIX del focus magic (che ora pare funzionare correttamente) la spell ARCANE MISSILE non funziona più. Quando la si utilizza, non succede nulla, non fa danno, non lancia i missili, non consuma mana e attiva solo il global cd. L'animazione (Il pg porta la mano avanti verso il bersaglio) funziona correttamente ma nessun missile viene lanciato. 
P.S.
Il primo bonus T10 si attiva correttamente se la spell viene usata con il proc Arcane Barrage UP perchè consuma il buff pur non producendo alcun danno.
.
Inutile dire che il bug è gravissimo e che la spec arcane sia pvp che pve è completamente inutilizzabile.

**Comment by Yehonal** [comment]
Il bug è stato fixato subito dopo la tua segnalazione
