### ISSUE TITLE
(Rogue) Cloak of Shadow non blocca i dot di Icy Touch e Chains of Ice.

### ISSUE THREAD

**Issue by Kickassbro** [AzerothShard/AzerothShard-Ita-Wotlk#33]
Le spell ICY TOUCH (http://wotlk.openwow.com/spell=49909) e CHAINS OF ICE (http://wotlk.openwow.com/spell=45524) ignorano il fattore resist (-90%) della spell del Rogue CLOAK OF SHADOW (http://wotlk.openwow.com/spell=65961).

In particolare, con Cloak of Shadow up sul rogue, la spell Icy Touch fà danno istant e applica i Desease  del Frost Fever (http://wotlk.openwow.com/spell=55095).
La spell Chains of Ice invece non intrappola il personaggio a terra (com'è giusto che sia) però applica comunque i dot del Frost Fever ignorando tutte le volte il fattore resist del Cos.

Ho fatto test anche con altri dot di altre classi provando in caso fosse un problema delle spell frost ma non risulta esserlo. Il mago di frostbolt non applica gli snared effect col Cloak of shadow up nè freeza per terra. Ho provato anche con altre spell di altri rami come il fire e non applica dot. Ho provato col dk il plague strike e non applica dot.

Proverò a fare altri test con altre classi ma per ora In conclusione solo con le due spell del Dk citate a inizio post ci sono problemi, a questo punto deduco che il CoS sia corretto ma che le spell Icy Touch e Chains of Ice abbiano qualcosa che non va.

**Comment by pati3nc3** [comment]
Il chain s of ice funziona proprio così sul cos, deve applicare i debuff ... prova su qualsiasi altro server

**Comment by Jagermaister95** [comment]
Testato più e più volte e l'icy touch non entra sempre rispettanto il 90% della resistenza mentre per il chain è giusto che entri il debuff ma effettivamente il rallentamento entra quasi sempre vanificando il cloak su quest spell

**Comment by Kickassbro** [comment]
Il chains of ice deve applicare i debuff ma non sempre sul cos, deve rispettare la resistenza come tutte le altre spell non melee.
Se mi fai leggere da qualche parte che il debuff del chains deve entrare sul cos va bene, ma su tutti i server su cui sono stato non era così. 
E' pur sempre una spell non un attacco melee che entra sicuro.
Per quanto riguarda l'icy touch TUTTE le volte che l'ho testato io col mio rogue e con un dk che aveva SOLO 25 spell penetration entrava al 100% su cos up. L'ho provato più di 10 volte e tutte le volte è entrato. Sono disposto anche a fare dei test con voi non ho problemi.

**Comment by pati3nc3** [comment]
Da player con 10 anni di gaming ti posso assicurare che se metti 0 spel penetration su un dk e fai chain sul cos entrer? comunque il dot, ? proprio una meccanica del gioco

Il giorno 14 giu 2016, alle ore 18:52, Kickassbro <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Il chains of ice deve applicare i debuff ma non sempre sul cos, deve rispettare la resistenza come tutte le altre spell non melee.
Se mi fai leggere da qualche parte che il debuff del chains deve entrare sul cos va bene, ma su tutti i server su cui sono stato non era cos?.
E' pur sempre una spell non un attacco melee che entra sicuro.
Per quanto riguarda l'icy touch TUTTE le volte che l'ho testato io col mio rogue e con un dk che aveva SOLO 25 spell penetration entrava al 100% su cos up. L'ho provato pi? di 10 volte e tutte le volte ? entrato. Sono disposto anche a fare dei test con voi non ho problemi.

-

**Comment by mik1893** [comment]
non e un bug, era cosi su wotlk.
http://us.battle.net/wow/en/forum/topic/9422973273 

primo risultato ricerca google Cloak of Shadows vs dk diseases
