### ISSUE TITLE
Talent Paladin Holy  [Light's Grace]

### ISSUE THREAD

**Issue by Redina8** [AzerothShard/AzerothShard-Ita-Wotlk#36]
non riduce le Holy Light di 0,5 secondi ma di 0,39 secondi

**Comment by mik1893** [comment]
ciao, 
riduce le holy light di un valore che quando hai haste 0 e' 0,5 secondi, ma se hai dell haste, il valore diminuisce - perche diminuisce il cast della holy light gia di per se con l haste.

In buona sostanza, bilancia il decremento del cast della spell con l haste presente sul personaggio

Il talento e' working as intended, come e' spiegato qua:
https://github.com/TrinityCore/TrinityCore/issues/5008 

"About Light’s Grace, it has a very confusing tooltip. It’s easy to interpret it as a ,5 second base cast time reduction, while it is in fact another multiplicative haste modifier of 20%. Henceforth, Light’s Grace suffers from absolute diminishing value (but not relative!) like any other haste effect, and only gives ,5 second absolute cast time reduction at 0 haste."
