### ISSUE TITLE
bug istant 80 

### ISSUE THREAD

**Issue by slysal** [AzerothShard/AzerothShard-Ita-Wotlk#67]
ho appena creato il pg al livello 80 ma alla prima volta che provo ad entrare mi dice che si diconnette dal server, e cosi tutte le volte che provo ad entrare mi dice la stessa cosa e non posso ne entrare con il pg ne giocare

**Comment by Arkan0r** [comment]
Non è un bug, bisogna prima risolvere le flag di customizzazione
