### ISSUE TITLE
Impossibile connettersi

### ISSUE THREAD

**Issue by Nokastu** [AzerothShard/AzerothShard-Ita-Wotlk#68]
Attualmente riscontro questo problema, non riesco a connettermi. Ci sono attualmente 114 players online, però ricevo questo errore quando cerco di connettermi. 
![wowscrnshot_070716_175718](https://cloud.githubusercontent.com/assets/20341746/16659950/942f6642-446c-11e6-857d-102c126b1fe1.jpg)

**Comment by Yehonal** [comment]
https://azerothshard.org/forums/support
